kind: pipeline
type: ssh
name: test-ssh

server:
  host: https://tysondrone.digitalstacks.net/
  user: ubuntu
  password:
    from_secret: password

steps:
- name: greeting
  commands:
  - echo hello world
